- name: Run docker compose up inside the VM
  hosts: inception_hosts

  tasks:
    - name: Bringing up the docker environment
      community.docker.docker_compose_v2:
        project_src: ~/inception
        wait: true
