- name: Run docker compose down inside the VMs
  hosts: inception_hosts

  tasks:
    - name: Destroying the docker environment
      community.docker.docker_compose_v2:
        project_src: ~/inception
        state: absent
        wait: true
